---
- hosts: all_datacenters
  connection: local
  gather_facts: False

  tasks:

    - name: get show run output
      ios_command:
        commands:
          - show run | i ntp server

      register: my_output
    - debug:
        var: my_output.stdout_lines

    - name: remove all ntp servers
      # loop through my_output.stdout_lines "list"
      with_items: "{{ my_output.stdout_lines }}"
      ios_config:
        lines:
          - no {{ item }}
      # only execut ios_config/lines when the line below is "true"
      # e.g. if the value of "item" as we look is "not" in our
      when: 'item not in global_servers.ntp_servers'




